services:
  postgres:
    image: postgres:16
    container_name: v360_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} || exit 1",
        ]
      interval: 5s
      timeout: 5s
      retries: 30

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: v360_pgadmin
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ES_VERSION}
    container_name: v360_es
    environment:
      discovery.type: single-node
      xpack.security.enabled: "true"
      ELASTIC_PASSWORD: ${ES_PASSWORD}
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "${ES_HTTP_PORT}:9200"
    healthcheck:
      # return healthy on 200 (OK) or 401 (Unauthorized when not passing creds)
      test: ["CMD-SHELL", "sh -c \"code=$(curl -s -o /dev/null -w '%{http_code}' -u elastic:${ES_PASSWORD} http://localhost:9200 || echo 000); echo \\$code; [ \\$code -eq 200 -o \\$code -eq 401 ]\""]
      interval: 10s
      timeout: 5s
      retries: 30
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:${ES_VERSION}
    container_name: v360_kibana
    depends_on:
      elasticsearch:
        condition: service_healthy
    environment:
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
      ELASTICSEARCH_USERNAME: elastic
      ELASTICSEARCH_PASSWORD: ${ES_PASSWORD}
    ports:
      - "${KIBANA_PORT}:5601"

  arangodb:
    image: arangodb:3.11
    container_name: v360_arango
    environment:
      ARANGO_ROOT_PASSWORD: ${ARANGO_ROOT_PASSWORD}
    ports:
      - "${ARANGO_PORT}:8529"
    volumes:
      - arangodata:/var/lib/arangodb3

  mailhog:
    image: mailhog/mailhog
    container_name: v360_mailhog
    ports:
      - "${MAILHOG_SMTP}:1025"
      - "${MAILHOG_UI}:8025"

volumes:
  pgdata: {}
  esdata: {}
  arangodata: {}
